### ISSUE TITLE
very minor issue when saving parameter files

### ISSUE THREAD

**Issue by Yixuan39** [xji3/IGCexpansion#12]
Hello Xiang,
I think for this line, we should change it to `save_file = self.path + self.save_name`. I found it when I specify save_path and save_name at the same time. The parameter file is saved as the same directory as the script. However, I think this is a very minor issue, it doesn't affect the software successfully running.
Reference:
https://github.com/xji3/IGCexpansion/blob/c7cc5d727f8d790adeb7ebf50a033eb01efdb574/IGCexpansion/CodonGeneconv.py#L1661

**Comment by xji3** [comment]
I prefer not changing.  The logic is that if you provide `save_path` for the location, then a name is generated.  Otherwise, if you provide an exact name with location, nothing else should be done.  `save_name` should contain the full path to the location + name of the file.

**Comment by Yixuan39** [comment]
Thank you for the explanation! I agree with you.
